# -*- coding: utf-8 -*-
"""double-ended queue-Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Es0bQmSM77_8J8kU6mraYOxNIST8xnrx
"""

from collections import deque

stack = deque()

# Push
stack.append(1)
stack.append(2)

# Peek
print(stack[-1])

# Pop
print(stack.pop())

# isEmpty
print(len(stack) == 0)