# -*- coding: utf-8 -*-
"""Encapsulation-Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frk52VrOxNJuJZyyFpbQZsdXIUfmDACn
"""

class Person:
    def __init__(self, name):
        self.__name = name  # Private attribute

    def get_name(self):
        return self.__name

p = Person("khan bhai")
print(p.get_name())